### PR TITLE
 Wait for images to load to populate EXIF data

### LINKED ISSUE #16: Image metadata
The metadata of image doesn't display on the first click but it displays on the second click.

Repro:
Just open the same image twice by clicking on the thumbnail. After second click you will see metadata.

### PR DESCRIPTION
**Pull request by Niduroki**
Closes #16

Waiting for images to be ready, to read their exif data now

This might conflict with https://github.com/rampatra/photography/pull/44 because `main.min.js` is changed differently in each branch. I can minify it again/rebase this branch and minify if necessary (or alternatively feel free to do it yourself).

### CODE REVIEW

**Comment by rampatra** [comment]
This looks like a useful PR, would it be possible to reopen this, please?

**Comment by Niduroki** [comment]
If you (after 3,5 years of no comment) still care about this PR feel free to copy the provided code and merge it yourself.

This PR can be considered as MIT-licensed, thus do what you want with the code.
There is no way of reopening this PR, since I have deleted the original repo.

**Comment by rampatra** [comment]
I am not sure how but I missed this PR. I didn't get an email about this PR in my inbox. Anyway, thanks for your comment, I'll add it to the repo.

Thanks again for your time.

**Comment by rampatra** [comment]
Changes added to master!

**Pull request closed without merging**
